DOSSIER_ENTREPRISE_FROM_PM_HEADER_MAPPING = {
  date_1re_immatriculation: :date_premiere_immatriculation,
  date_debut_1re_activite: :date_debut_premiere_activite,
  date_greffe: :date_derniere_modification,
  libelle_evt: :libelle_derniere_modification,
  denomination: nil,
  forme_juridique: nil,
  sigle: nil,
  associe_unique: nil,
  activite_principale: nil,
  type_capital: nil,
  capital_actuel: nil,
  capital: nil,
  date_cloture: nil,
  devise: nil,
  date_cloture_except: nil,
  economie_sociale_solidaire: nil,
  duree_pm: nil,
}
