PM_HEADER_MAPPING = {
  date_greffe: :date_derniere_modification,
  libelle_evt: :libelle_derniere_modification,
  date_cloture_except: :date_cloture_exeptionnelle,
  nom_greffe: nil,
  date_1re_immatriculation: nil,
  date_debut_1re_activite: nil,
  type_inscription: nil,
  date_immatriculation: nil,
  date_radiation: nil,
  date_transfert: nil,
  sans_activite: nil,
  date_debut_activite: nil,
  date_cessation_activite: nil,
}
